apps:

- name: app
  script: ./index.js
  exec_mode: cluster
  instances : 2
  watch: false
  max_memory_restart: "200M"

#   script: './service-worker/',
#   watch: ['./service-worker']
#   apps : [{
#     script: 'index.js',
#   }, {
#   }],

#   deploy : {
#     production : {
#       user : 'SSH_USERNAME',
#       host : 'SSH_HOSTMACHINE',
#       ref  : 'origin/master',
#       repo : 'GIT_REPOSITORY',
#       path : 'DESTINATION_PATH',
#       'pre-deploy-local': '',
#       'post-deploy' : 'npm install && pm2 reload ecosystem.config.js --env production',
#       'pre-setup': ''
#     }
#   }
# };
